# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).
  scrape_timeout: 10s

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090']

  - job_name: blackbox_exporter_google
    static_configs:
    - targets: ['localhost:9115']
    metrics_path: /probe
    params:
      target: ['google.com']
      module: ['http_2xx']
    scheme: http

  - job_name: recursos_fisicos
    static_configs:
    - targets: ['host.docker.internal:9100']
    metrics_path: /metrics
    scheme: http

  - job_name: sitio_de_paw
    static_configs:
    - targets: ['localhost:5000']
    metrics_path: /search_flow
    scheme: http
    scrape_interval: 3s

  - job_name: sitio_de_paw_demora
    static_configs:
    - targets: ['localhost:9115']
    metrics_path: /probe
    params:
      target: ['host.docker.internal:8081/webapp/a_long_time']
      module: ['http_2xx']
    scheme: http

  - job_name: pop3_server1
    static_configs:
    - targets: ['localhost:9115']
    metrics_path: /probe
    params:
      target: ['host.docker.internal:110']
      module: ['pop3s_banner']

  - job_name: pop3_server2
    static_configs:
    - targets: ['localhost:9115']
    metrics_path: /probe
    params:
      target: ['host.docker.internal:112']
      module: ['pop3s_banner']

  - job_name: ssh_server1
    static_configs:
    - targets: ['localhost:9115']
    metrics_path: /probe
    params:
      target: ['host.docker.internal:22']
      module: ['ssh_banner']

  - job_name: ssh_server2
    static_configs:
    - targets: ['localhost:9115']
    metrics_path: /probe
    params:
      target: ['host.docker.internal:23']
      module: ['ssh_banner']
